name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Release
      env:
        GRAVITYFORM_LICENSE_KEY: ${{ secrets.GRAVITYFORM_LICENSE_KEY }}
      run: php .github/scripts/release.php
